# Generated by Django 3.1 on 2020-08-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20200821_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='name',
            field=models.CharField(default='Point', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='points',
            name='text',
            field=models.TextField(default="It's text about point"),
            preserve_default=False,
        ),
    ]
