# Generated by Django 3.1 on 2020-08-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Links',
        ),
    ]
