# Generated by Django 3.1 on 2020-09-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chronology',
            name='file',
            field=models.FileField(default=1, upload_to='files'),
            preserve_default=False,
        ),
    ]
